# Site settings
title: Anthony Matsas
email: amatsas@outlook.com
description: > 
  I am a computer science student in Chicago, attending Lewis University.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://anthonymatsas.com" # the base hostname & protocol for your site
twitter_username: tonymatsas
github_username:  anthonymatsas

# Build settings
markdown: kramdown
